"""Populate the DEV custom_universe_master with the operator-approved
Phase 1B symbol list (Option B — ₹20–₹500 moderate band, 23 symbols).

DEV ONLY — never run this against production.
Run from artifacts/api-server/src/python/:
    python3 scripts/populate_dev_custom_universe.py
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone

# Guard: refuse to run if DATABASE_URL looks like the production host.
import os
_db_url = os.environ.get("DATABASE_URL", "")
if "nse-trade-intraday.replit.app" in _db_url or "prod" in _db_url.lower():
    print(json.dumps({
        "success": False,
        "error": "REFUSED — DATABASE_URL looks like production. Use dev only.",
    }))
    sys.exit(1)

NOW_ISO = datetime.now(timezone.utc).isoformat()

# Operator-approved Phase 1B list — Option B (₹20–₹500)
# Prices and volumes verified via yfinance 2026-08-21.
# Kite instrument_token = None until Kite instrument cache is synced.
SYMBOLS = [
    # ── IT ─────────────────────────────────────────────────────────────────
    {
        "symbol": "WIPRO",
        "company_name": "Wipro Ltd",
        "sector": "IT",
        "industry": "IT Services",
        "yahoo_symbol": "WIPRO.NS",
        "kite_symbol": "WIPRO",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 180.79,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 4_635_652.0,
        "avg_turnover_20d": 837_793_780.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "Only qualifying IT name in Option B band; F&O stock; NIFTY_50 mapping verified",
        "reason_excluded": None,
    },
    # ── INFRA (13) ─────────────────────────────────────────────────────────
    {
        "symbol": "IRFC",
        "company_name": "Indian Railway Finance Corporation",
        "sector": "INFRA",
        "industry": "Infrastructure Finance",
        "yahoo_symbol": "IRFC.NS",
        "kite_symbol": "IRFC",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 86.40,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 4_765_907.0,
        "avg_turnover_20d": 411_774_365.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "PSU infra; high retail participation; yfinance verified",
        "reason_excluded": None,
    },
    {
        "symbol": "NBCC",
        "company_name": "NBCC India Ltd",
        "sector": "INFRA",
        "industry": "Construction",
        "yahoo_symbol": "NBCC.NS",
        "kite_symbol": "NBCC",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 88.88,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 5_369_124.0,
        "avg_turnover_20d": 477_101_524.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "PSU construction infra; budget-cycle sensitivity; good volumes",
        "reason_excluded": None,
    },
    {
        "symbol": "NMDC",
        "company_name": "NMDC Ltd",
        "sector": "INFRA",
        "industry": "Mining",
        "yahoo_symbol": "NMDC.NS",
        "kite_symbol": "NMDC",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 84.61,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 18_865_805.0,
        "avg_turnover_20d": 1_595_614_161.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "High volume mining PSU; commodity-sensitive; F&O-eligible",
        "reason_excluded": None,
    },
    {
        "symbol": "IRCON",
        "company_name": "IRCON International Ltd",
        "sector": "INFRA",
        "industry": "Construction",
        "yahoo_symbol": "IRCON.NS",
        "kite_symbol": "IRCON",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 124.72,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 909_714.0,
        "avg_turnover_20d": 113_439_133.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "PSU infra construction; decent volumes",
        "reason_excluded": None,
    },
    {
        "symbol": "HUDCO",
        "company_name": "Housing and Urban Development Corporation",
        "sector": "INFRA",
        "industry": "Infrastructure Finance",
        "yahoo_symbol": "HUDCO.NS",
        "kite_symbol": "HUDCO",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 186.09,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 875_044.0,
        "avg_turnover_20d": 162_892_441.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "PSU housing/urban infra finance; good retail participation",
        "reason_excluded": None,
    },
    {
        "symbol": "GAIL",
        "company_name": "GAIL India Ltd",
        "sector": "INFRA",
        "industry": "Gas Distribution",
        "yahoo_symbol": "GAIL.NS",
        "kite_symbol": "GAIL",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 172.00,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 6_509_016.0,
        "avg_turnover_20d": 1_119_550_752.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; high volume; gas price sensitive",
        "reason_excluded": None,
    },
    {
        "symbol": "SAIL",
        "company_name": "Steel Authority of India Ltd",
        "sector": "INFRA",
        "industry": "Steel",
        "yahoo_symbol": "SAIL.NS",
        "kite_symbol": "SAIL",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 173.46,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 14_683_544.0,
        "avg_turnover_20d": 2_545_956_062.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; very high volume; commodity infra proxy",
        "reason_excluded": None,
    },
    {
        "symbol": "MRPL",
        "company_name": "Mangalore Refinery and Petrochemicals Ltd",
        "sector": "INFRA",
        "industry": "Refinery",
        "yahoo_symbol": "MRPL.NS",
        "kite_symbol": "MRPL",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 176.81,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 6_535_381.0,
        "avg_turnover_20d": 1_155_220_276.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "HPCL subsidiary refinery; decent intraday volumes",
        "reason_excluded": None,
    },
    {
        "symbol": "RVNL",
        "company_name": "Rail Vikas Nigam Ltd",
        "sector": "INFRA",
        "industry": "Railway Infrastructure",
        "yahoo_symbol": "RVNL.NS",
        "kite_symbol": "RVNL",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 225.30,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 2_616_366.0,
        "avg_turnover_20d": 589_267_290.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "High retail participation; infra budget-driven; Option B band",
        "reason_excluded": None,
    },
    {
        "symbol": "RECLTD",
        "company_name": "REC Ltd",
        "sector": "INFRA",
        "industry": "Infrastructure Finance",
        "yahoo_symbol": "RECLTD.NS",
        "kite_symbol": "RECLTD",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 326.65,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 4_327_156.0,
        "avg_turnover_20d": 1_413_436_234.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; infrastructure lending PSU; high volume",
        "reason_excluded": None,
    },
    {
        "symbol": "NTPC",
        "company_name": "NTPC Ltd",
        "sector": "INFRA",
        "industry": "Power Generation",
        "yahoo_symbol": "NTPC.NS",
        "kite_symbol": "NTPC",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 340.00,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 6_532_622.0,
        "avg_turnover_20d": 2_221_091_480.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; very high volume; power sector proxy",
        "reason_excluded": None,
    },
    {
        "symbol": "PFC",
        "company_name": "Power Finance Corporation Ltd",
        "sector": "INFRA",
        "industry": "Infrastructure Finance",
        "yahoo_symbol": "PFC.NS",
        "kite_symbol": "PFC",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 363.00,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 9_592_260.0,
        "avg_turnover_20d": 3_481_990_380.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; power sector lending PSU; high volume",
        "reason_excluded": None,
    },
    {
        "symbol": "COALINDIA",
        "company_name": "Coal India Ltd",
        "sector": "INFRA",
        "industry": "Mining",
        "yahoo_symbol": "COALINDIA.NS",
        "kite_symbol": "COALINDIA",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 405.20,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 10_327_223.0,
        "avg_turnover_20d": 4_184_590_750.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "Very high volume; dividend play; commodity proxy",
        "reason_excluded": None,
    },
    # ── BANK (9) ───────────────────────────────────────────────────────────
    {
        "symbol": "IDFCFIRSTB",
        "company_name": "IDFC First Bank Ltd",
        "sector": "BANK",
        "industry": "Private Bank",
        "yahoo_symbol": "IDFCFIRSTB.NS",
        "kite_symbol": "IDFCFIRSTB",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 86.75,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 12_588_998.0,
        "avg_turnover_20d": 1_092_095_076.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "Very high volume private bank; F&O stock; retail favourite",
        "reason_excluded": None,
    },
    {
        "symbol": "PNB",
        "company_name": "Punjab National Bank",
        "sector": "BANK",
        "industry": "PSU Bank",
        "yahoo_symbol": "PNB.NS",
        "kite_symbol": "PNB",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 116.55,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 14_047_780.0,
        "avg_turnover_20d": 1_636_768_590.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; very high volume PSU bank; widely tracked",
        "reason_excluded": None,
    },
    {
        "symbol": "CANBK",
        "company_name": "Canara Bank",
        "sector": "BANK",
        "industry": "PSU Bank",
        "yahoo_symbol": "CANBK.NS",
        "kite_symbol": "CANBK",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 129.96,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 8_124_111.0,
        "avg_turnover_20d": 1_055_987_488.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; high volume PSU bank",
        "reason_excluded": None,
    },
    {
        "symbol": "BANKINDIA",
        "company_name": "Bank of India",
        "sector": "BANK",
        "industry": "PSU Bank",
        "yahoo_symbol": "BANKINDIA.NS",
        "kite_symbol": "BANKINDIA",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 142.79,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 5_333_928.0,
        "avg_turnover_20d": 761_513_821.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; solid PSU bank volumes",
        "reason_excluded": None,
    },
    {
        "symbol": "MAHABANK",
        "company_name": "Bank of Maharashtra",
        "sector": "BANK",
        "industry": "PSU Bank",
        "yahoo_symbol": "MAHABANK.NS",
        "kite_symbol": "MAHABANK",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 80.26,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 7_790_968.0,
        "avg_turnover_20d": 625_269_033.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "Good retail volumes; government-banking sensitive",
        "reason_excluded": None,
    },
    {
        "symbol": "UNIONBANK",
        "company_name": "Union Bank of India",
        "sector": "BANK",
        "industry": "PSU Bank",
        "yahoo_symbol": "UNIONBANK.NS",
        "kite_symbol": "UNIONBANK",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 183.45,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 6_916_849.0,
        "avg_turnover_20d": 1_268_599_331.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; solid PSU bank volumes",
        "reason_excluded": None,
    },
    {
        "symbol": "BANKBARODA",
        "company_name": "Bank of Baroda",
        "sector": "BANK",
        "industry": "PSU Bank",
        "yahoo_symbol": "BANKBARODA.NS",
        "kite_symbol": "BANKBARODA",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 247.00,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 7_914_129.0,
        "avg_turnover_20d": 1_954_789_863.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; very high volume PSU bank; widely covered",
        "reason_excluded": None,
    },
    {
        "symbol": "KTKBANK",
        "company_name": "Karnataka Bank Ltd",
        "sector": "BANK",
        "industry": "Private Bank",
        "yahoo_symbol": "KTKBANK.NS",
        "kite_symbol": "KTKBANK",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 328.30,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 3_431_080.0,
        "avg_turnover_20d": 1_125_423_544.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "South India private bank; decent volumes; Option B band",
        "reason_excluded": None,
    },
    {
        "symbol": "FEDERALBNK",
        "company_name": "Federal Bank Ltd",
        "sector": "BANK",
        "industry": "Private Bank",
        "yahoo_symbol": "FEDERALBNK.NS",
        "kite_symbol": "FEDERALBNK",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": True,
        "last_ltp": 361.00,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": 4_397_811.0,
        "avg_turnover_20d": 1_587_609_771.0,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": "F&O stock; high quality private bank; solid volumes",
        "reason_excluded": None,
    },
]

# Excluded (with documented reasons stored as inactive rows for audit)
EXCLUDED = [
    {
        "symbol": "IOB",
        "company_name": "Indian Overseas Bank",
        "sector": "BANK",
        "industry": "PSU Bank",
        "yahoo_symbol": "IOB.NS",
        "kite_symbol": "IOB",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": False,
        "last_ltp": 33.0,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": None,
        "avg_turnover_20d": None,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": None,
        "reason_excluded": "Excluded Phase 1B: very low absolute price (₹33); "
                           "spread/slippage risk at 757 shares per ₹25K cap",
    },
    {
        "symbol": "UCOBANK",
        "company_name": "UCO Bank",
        "sector": "BANK",
        "industry": "PSU Bank",
        "yahoo_symbol": "UCOBANK.NS",
        "kite_symbol": "UCOBANK",
        "instrument_token": None,
        "price_min": 20.0,
        "price_max": 500.0,
        "is_active": False,
        "last_ltp": 25.7,
        "last_ltp_source": "yfinance_close",
        "avg_volume_20d": None,
        "avg_turnover_20d": None,
        "ohlcv_available": True,
        "last_verified_at": NOW_ISO,
        "reason_included": None,
        "reason_excluded": "Excluded Phase 1B: very low absolute price (₹25.7); "
                           "spread/slippage risk at 972 shares per ₹25K cap",
    },
]


def main() -> None:
    sys.path.insert(0, ".")
    from custom_universe_store import upsert_symbols

    all_rows = SYMBOLS + EXCLUDED
    result = upsert_symbols(all_rows)

    active_count = sum(1 for r in all_rows if r["is_active"])
    excluded_count = sum(1 for r in all_rows if not r["is_active"])

    output = {
        "success": result.get("success", False),
        "upserted": result.get("upserted", 0),
        "active_symbols": active_count,
        "excluded_symbols": excluded_count,
        "total_rows": len(all_rows),
        "error": result.get("error"),
    }
    print(json.dumps(output, indent=2))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
