import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import tradingRouter from "./trading";
import streamRouter from "./stream";
import pipelineRouter, { startPipelineTail } from "./pipeline";
import backtestRouter from "./backtest";
import labRouter from "./lab";
import simulationRouter from "./simulation";
import certificationRouter from "./certification";
import phase239Router from "./phase239";
import phase12Router from "./phase12";
import phase13Router from "./phase13";
import phase14Router from "./phase14";
import phase15Router from "./phase15";
import phase16Router from "./phase16";
import phase17Router from "./phase17";
import phase18Router from "./phase18";
import phase21Router from "./phase21";
import phase22Router from "./phase22";
import phase4aRouter from "./phase4a";
import kiteRouter from "./kite";
import notificationsRouter from "./notifications";
import downloadRouter from "./download";
import reconciliationRouter from "./reconciliation";
import portfolioRouter from "./portfolio";
import preopenRouter from "./preopen";
import preopenValidationRouter from "./preopen-validation";
import signalValidationRouter from "./signalValidation";
import executionQualityRouter from "./executionQuality";
import performanceRouter from "./performance";
import strategyRouter from "./strategy";
import aiPerformanceRouter from "./ai-performance";
import executiveRouter from "./executive";
import validationRouter from "./validation";
import optimisationRouter from "./optimisation";
import aiOptimisationRouter from "./ai-optimisation";
import riskOptimisationRouter from "./risk-optimisation";
import readinessRouter from "./readiness";
import marketIntelligenceRouter from "./market-intelligence";
import eventIntelligenceRouter from "./event-intelligence";
import macroIntelligenceRouter from "./macro-intelligence";
import explainableAiRouter from "./explainable-ai";
import phase27Router from "./phase27";
import researchLabRouter       from "./research-lab";
import observabilityRouter     from "./observability";
import paperAnalyticsRouter    from "./paper-analytics";
import dataQualityRouter       from "./data-quality";
import riskValidationRouter    from "./risk-validation";
import operationsRouter        from "./operations";
import securityRouter          from "./security";
import deploymentRouter        from "./deployment";
import commandCenterRouter     from "./command-center";
import agentFrameworkRouter    from "./agentFramework";
import { analysisAgentsRouter }     from "./analysisAgents";
import { decisionLayerRouter }      from "./decisionLayer";
import { learningLayerRouter }      from "./learningLayer";
import { collaborationEngineRouter } from "./collaborationEngine";
import { autonomousOpsRouter }      from "./autonomousOps";
import phase11Router                from "./phase11";
import replayRouter                 from "./replay";
import e2eValidationRouter          from "./e2e-validation";
import liveValidationRouter         from "./live-validation";
import phase26cValidationRouter     from "./phase26c-validation";
import phase26dReportsRouter        from "./phase26d-reports";
import validationV2Router           from "./validation-v2";
import phase24Router from "./phase24";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(streamRouter);
router.use(pipelineRouter);
router.use(backtestRouter);
router.use(labRouter);
router.use(simulationRouter);
router.use(certificationRouter);
router.use(phase239Router);
startPipelineTail();
router.use(portfolioRouter);
router.use(phase12Router);
router.use(phase13Router);
router.use(phase14Router);
router.use(phase15Router);
router.use(phase16Router);
router.use(phase17Router);
router.use(phase18Router);
router.use(phase21Router);
router.use(phase22Router);
router.use(phase24Router);
router.use(phase4aRouter);
router.use(kiteRouter);
router.use(notificationsRouter);
router.use(reconciliationRouter);
router.use(preopenRouter);
router.use(preopenValidationRouter);
router.use(signalValidationRouter);
router.use(executionQualityRouter);
router.use(performanceRouter);
router.use(strategyRouter);
router.use(aiPerformanceRouter);
router.use(executiveRouter);
router.use(validationRouter);
router.use(optimisationRouter);
router.use(aiOptimisationRouter);
router.use(riskOptimisationRouter);
router.use(readinessRouter);
router.use(marketIntelligenceRouter);
router.use(eventIntelligenceRouter);
router.use(macroIntelligenceRouter);
router.use(explainableAiRouter);
router.use(phase27Router);
router.use(researchLabRouter);
router.use(observabilityRouter);
router.use(paperAnalyticsRouter);
router.use(dataQualityRouter);
router.use(riskValidationRouter);
router.use(operationsRouter);
router.use(securityRouter);
router.use(deploymentRouter);
router.use(commandCenterRouter);
router.use(agentFrameworkRouter);
router.use(analysisAgentsRouter);
router.use(decisionLayerRouter);
router.use(learningLayerRouter);
router.use(collaborationEngineRouter);
router.use(autonomousOpsRouter);
router.use("/phase11", phase11Router);
router.use(replayRouter);
router.use(e2eValidationRouter);
router.use(liveValidationRouter);
router.use(phase26cValidationRouter);
router.use(phase26dReportsRouter);
router.use(validationV2Router);
router.use(tradingRouter);
router.use(downloadRouter);

export default router;
