import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import tradingRouter from "./trading";
import streamRouter from "./stream";
import phase12Router from "./phase12";
import phase13Router from "./phase13";
import phase14Router from "./phase14";
import phase15Router from "./phase15";
import phase16Router from "./phase16";
import phase17Router from "./phase17";
import phase18Router from "./phase18";
import phase21Router from "./phase21";
import phase22Router from "./phase22";
import phase4aRouter from "./phase4a";
import kiteRouter from "./kite";
import notificationsRouter from "./notifications";
import downloadRouter from "./download";
import reconciliationRouter from "./reconciliation";
import portfolioRouter from "./portfolio";
import preopenRouter from "./preopen";
import preopenValidationRouter from "./preopen-validation";
import signalValidationRouter from "./signalValidation";
import executionQualityRouter from "./executionQuality";
import performanceRouter from "./performance";
import strategyRouter from "./strategy";
import aiPerformanceRouter from "./ai-performance";
import executiveRouter from "./executive";
import validationRouter from "./validation";
import optimisationRouter from "./optimisation";
import aiOptimisationRouter from "./ai-optimisation";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(streamRouter);
router.use(portfolioRouter);
router.use(phase12Router);
router.use(phase13Router);
router.use(phase14Router);
router.use(phase15Router);
router.use(phase16Router);
router.use(phase17Router);
router.use(phase18Router);
router.use(phase21Router);
router.use(phase22Router);
router.use(phase4aRouter);
router.use(kiteRouter);
router.use(notificationsRouter);
router.use(reconciliationRouter);
router.use(preopenRouter);
router.use(preopenValidationRouter);
router.use(signalValidationRouter);
router.use(executionQualityRouter);
router.use(performanceRouter);
router.use(strategyRouter);
router.use(aiPerformanceRouter);
router.use(executiveRouter);
router.use(validationRouter);
router.use(optimisationRouter);
router.use(aiOptimisationRouter);
router.use(tradingRouter);
router.use(downloadRouter);

export default router;
