CREATE TABLE "alert_deliveries" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"idempotency_key" text NOT NULL,
	"channel" text NOT NULL,
	"kind" text NOT NULL,
	"severity" text DEFAULT 'INFO' NOT NULL,
	"title" text NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"destination" text NOT NULL,
	"payload" jsonb,
	"status" text DEFAULT 'QUEUED' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"max_attempts" integer DEFAULT 6 NOT NULL,
	"critical" boolean DEFAULT false NOT NULL,
	"dead_letter" boolean DEFAULT false NOT NULL,
	"next_attempt_at" timestamp with time zone DEFAULT now(),
	"expires_at" timestamp with time zone,
	"last_error" text,
	"provider_id" text,
	"provider_response" jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"delivered_at" timestamp with time zone,
	CONSTRAINT "alert_deliveries_idempotency_key_unique" UNIQUE("idempotency_key")
);
